import { auth } from "@/auth";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import AuthSessionProvider from "./_components/auth/auth-session-provider";
import MuiProvider from "./_components/mui/mui-provider";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <AuthSessionProvider session={session}>
          <MuiProvider>{children}</MuiProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
